// =============================================================================
// DAX MEASURES F칐R F칐RS츿LJNINGSANALYS
// =============================================================================
// Kopiera dessa measures till Power BI f칬r att anv칛nda dem.
// Be Claude f칬rklara eller modifiera efter behov.

// -----------------------------------------------------------------------------
// GRUNDL츿GGANDE MEASURES
// -----------------------------------------------------------------------------

// Total f칬rs칛ljning
Total F칬rs칛ljning =
SUM('F칬rs칛ljning'[Belopp])

// Antal order
Antal Order =
COUNTROWS('F칬rs칛ljning')

// Genomsnittligt orderv칛rde
Snitt Orderv칛rde =
DIVIDE(
    [Total F칬rs칛ljning],
    [Antal Order],
    0
)

// Antal unika kunder
Unika Kunder =
DISTINCTCOUNT('F칬rs칛ljning'[KundID])

// -----------------------------------------------------------------------------
// TIDSINTELLIGENS
// -----------------------------------------------------------------------------

// F칬rs칛ljning samma period f칬rra 친ret
F칬rs칛ljning F칀 =
CALCULATE(
    [Total F칬rs칛ljning],
    SAMEPERIODLASTYEAR('Datum'[Datum])
)

// F칬r칛ndring mot f칬rra 친ret (%)
YoY % =
VAR F칬rr칀r = [F칬rs칛ljning F칀]
VAR Detta칀r = [Total F칬rs칛ljning]
RETURN
DIVIDE(
    Detta칀r - F칬rr칀r,
    F칬rr칀r,
    BLANK()
)

// Ackumulerat hittills i 친r (YTD)
F칬rs칛ljning YTD =
CALCULATE(
    [Total F칬rs칛ljning],
    DATESYTD('Datum'[Datum])
)

// Rullande 12 m친nader
F칬rs칛ljning R12 =
CALCULATE(
    [Total F칬rs칛ljning],
    DATESINPERIOD(
        'Datum'[Datum],
        MAX('Datum'[Datum]),
        -12,
        MONTH
    )
)

// F칬reg친ende m친nad
F칬rs칛ljning FM =
CALCULATE(
    [Total F칬rs칛ljning],
    PREVIOUSMONTH('Datum'[Datum])
)

// F칬r칛ndring mot f칬reg친ende m친nad (%)
MoM % =
VAR F칬rraM친nad = [F칬rs칛ljning FM]
VAR DennaM친nad = [Total F칬rs칛ljning]
RETURN
DIVIDE(
    DennaM친nad - F칬rraM친nad,
    F칬rraM친nad,
    BLANK()
)

// -----------------------------------------------------------------------------
// RANKING OCH PARETO
// -----------------------------------------------------------------------------

// Rank produkter efter f칬rs칛ljning
Produkt Rank =
RANKX(
    ALL('Produkt'[Produktnamn]),
    [Total F칬rs칛ljning],
    ,
    DESC,
    DENSE
)

// Ackumulerad f칬rs칛ljningsandel (f칬r Pareto)
Kumulativ Andel =
VAR NuvarandeV칛rde = [Total F칬rs칛ljning]
VAR TotalV칛rde = CALCULATE(
    [Total F칬rs칛ljning],
    ALL('Produkt')
)
VAR KumulativtV칛rde =
    SUMX(
        FILTER(
            ALL('Produkt'),
            [Total F칬rs칛ljning] >= NuvarandeV칛rde
        ),
        [Total F칬rs칛ljning]
    )
RETURN
DIVIDE(KumulativtV칛rde, TotalV칛rde)

// -----------------------------------------------------------------------------
// VILLKORLIGA MEASURES
// -----------------------------------------------------------------------------

// F칬rs칛ljning endast f칬r nya kunder (f칬rsta k칬p senaste 90 dagarna)
F칬rs칛ljning Nya Kunder =
VAR NyaKunder =
    CALCULATETABLE(
        VALUES('Kund'[KundID]),
        FILTER(
            ALL('F칬rs칛ljning'),
            'F칬rs칛ljning'[Orderdatum] >= TODAY() - 90
        )
    )
RETURN
CALCULATE(
    [Total F칬rs칛ljning],
    'Kund'[KundID] IN NyaKunder
)

// F칬rs칛ljning med dynamisk valuta-formatering
F칬rs칛ljning Formaterad =
VAR V칛rde = [Total F칬rs칛ljning]
RETURN
SWITCH(
    TRUE(),
    V칛rde >= 1000000, FORMAT(V칛rde / 1000000, "#,##0.0") & " Mkr",
    V칛rde >= 1000, FORMAT(V칛rde / 1000, "#,##0") & " tkr",
    FORMAT(V칛rde, "#,##0") & " kr"
)

// -----------------------------------------------------------------------------
// KPI MED TRAFIKLJUS
// -----------------------------------------------------------------------------

// KPI-ikon baserat p친 m친luppfyllelse
KPI Ikon =
VAR Utfall = [Total F칬rs칛ljning]
VAR M친l = [F칬rs칛ljningsm친l]  -- Referera till din m친l-measure
VAR Uppfyllelse = DIVIDE(Utfall, M친l, 0)
RETURN
SWITCH(
    TRUE(),
    Uppfyllelse >= 1.0, "游릭",      -- 칐ver m친l
    Uppfyllelse >= 0.9, "游리",      -- N칛ra m친l (90%+)
    "游댮"                            -- Under m친l
)


// =============================================================================
// TIPS F칐R CLAUDE CODE:
// =============================================================================
// Kopiera en measure och be Claude:
// - "F칬rklara denna DAX-measure steg f칬r steg"
// - "Optimera denna measure f칬r b칛ttre prestanda"
// - "Skapa en liknande measure f칬r [annat m친tt]"
// - "L칛gg till felhantering f칬r tomma v칛rden"
